export const WORLDS = {
  urban: {
    id: 'urban',
    label: 'Urban',
    tagline: 'Engineered for the city.',
    bg: '#f5efe6',
    accent: '#c4a35a',
    text: '#2a2520',
    filter: 'none',
    cursor: 'compass',
    ambient: 'noise',
  },
  trail: {
    id: 'trail',
    label: 'Trail',
    tagline: 'Built for the detour.',
    bg: '#e8ddd0',
    accent: '#8a7a60',
    text: '#3d342b',
    filter: 'contrast(1.05) saturate(0.95)',
    cursor: 'leaf',
    ambient: 'fog',
  },
  technical: {
    id: 'technical',
    label: 'Technical',
    tagline: 'Precision in every thread.',
    bg: '#f0f0f0',
    accent: '#c4a35a',
    text: '#1a1a1a',
    filter: 'contrast(1.1) brightness(1.02)',
    cursor: 'crosshair',
    ambient: 'grid',
  },
  future: {
    id: 'future',
    label: 'Future',
    tagline: 'Ahead of the curve.',
    bg: '#111111',
    accent: '#ffd700',
    text: '#f0f0f0',
    filter: 'contrast(1.15) brightness(0.95)',
    cursor: 'reticle',
    ambient: 'scanline',
  },
};
